name: my_bill
description: "个人记账应用 - 支持多种记账方式的智能财务管理工具"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理
  provider: ^6.1.1
  
  # 网络请求
  dio: ^5.4.0
  
  # 图表展示
  fl_chart: ^0.65.0
  
  # 本地存储
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # 图片选择
  image_picker: ^1.0.4
  
  # 权限管理
  permission_handler: ^11.1.0
  
  # UI组件
  cupertino_icons: ^1.0.8
  
  # 日期时间处理
  intl: ^0.19.0
  
  # 路径处理
  path: ^1.8.3
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # 加密
  crypto: ^3.0.3
  
  # 设备信息
  device_info_plus: ^9.1.1
  
  # 网络连接检测
  connectivity_plus: ^5.0.2
  
  # 文件选择
  file_picker: ^6.1.1
  
  # UUID生成
   uuid: ^4.2.1
  
  # 依赖注入
  get_it: ^7.7.0
  
  # 对象比较
  equatable: ^2.0.5
  
  # 生物识别
  local_auth: ^2.1.8
  local_auth_android: ^1.0.38
  local_auth_ios: ^1.0.17
  
  # 本地通知
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # 语音识别
  speech_to_text: ^6.6.2
  
  # OCR文字识别
  google_mlkit_text_recognition: ^0.10.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码规范检查
  flutter_lints: ^5.0.0
  
  # JSON序列化代码生成
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # 测试相关
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  # 资源文件配置
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
  
  # 字体配置
  fonts:
    - family: PingFang
      fonts:
        - asset: assets/fonts/PingFang-Regular.ttf
        - asset: assets/fonts/PingFang-Medium.ttf
          weight: 500
        - asset: assets/fonts/PingFang-Bold.ttf
          weight: 700

# 国际化配置
flutter_intl:
  enabled: true
  class_name: S
  main_locale: zh_CN
  arb_dir: lib/l10n
  output_dir: lib/generated
